@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePlayerList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniquePlayerList
UniqueTagList -[hidden]down- UniquePlayerList

UniqueTagList -right-> "*" Tag
UniquePlayerList -right-> Player

Player -up-> "*" Tag

Player *--> Name
Player *--> Phone
Player *--> Email
Player *--> Address
@enduml
